# Generated by Django 3.1.2 on 2020-10-14 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20201014_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 11, 25, 55, 323233, tzinfo=utc)),
        ),
    ]
