# Generated by Django 3.1.2 on 2020-10-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20201014_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(default='password', max_length=20),
            preserve_default=False,
        ),
    ]
